# Generated by Django 4.2.8 on 2023-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_ASSEMBLY', 'Сборка заказа'), ('PAID', 'Заказ оплачен')], db_index=True, default='IN_ASSEMBLY', max_length=20, verbose_name='Стутус заказа')),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Оплачен в')),
                ('items', models.ManyToManyField(related_name='orders', to='payment.item', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
