# Generated by Django 4.2.8 on 2023-12-27 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Название')),
                ('duration', models.CharField(choices=[('forever', 'Навсегда'), ('once', 'Одноразовый'), ('repeating', 'Повторяющийся')], db_index=True, verbose_name='Продолжительность')),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Действителен до')),
                ('percent_off', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Процент скидки')),
            ],
        ),
    ]
